import { assertEquals } from "@std/assert";
import * as mod from "../src/mod.ts";
import * as adapters from "../src/adapters.ts";

// Type-level surface check: these must all be importable as types from the root.
// (Types are erased at runtime, so this is a compile-time assertion only.)
import type {
	Adapter,
	BackoffStrategy,
	BodyAbsentReason,
	BodyFactory,
	CircuitBreakerOptions,
	CircuitState,
	CircuitStateChange,
	CreateFetcherOptions,
	DeadlineGuardOptions,
	Fetcher,
	FetcherEvents,
	FetchFn,
	FetchLayer,
	FetchRequest,
	FetchResult,
	FetchTiming,
	HttpErrorGuardOptions,
	HttpMethod,
	Logger,
	ObservabilityOptions,
	PageFetchErrorInit,
	PageFetchErrorKind,
	ReplayableBody,
	RetryInfo,
	RetryOptions,
	RetryOutcome,
	TimeoutGuardOptions,
	UnsupportedTypePolicy,
} from "../src/mod.ts";

// one entry per imported type — kept in the same order, so a stale name is obvious
type _Surface = [
	Adapter,
	BackoffStrategy,
	BodyAbsentReason,
	BodyFactory,
	CircuitBreakerOptions,
	CircuitState,
	CircuitStateChange,
	CreateFetcherOptions,
	DeadlineGuardOptions,
	Fetcher,
	FetcherEvents,
	FetchFn,
	FetchLayer,
	FetchRequest,
	FetchResult,
	FetchTiming,
	HttpErrorGuardOptions,
	HttpMethod,
	Logger,
	ObservabilityOptions,
	PageFetchErrorInit,
	PageFetchErrorKind,
	ReplayableBody,
	RetryInfo,
	RetryOptions,
	RetryOutcome,
	TimeoutGuardOptions,
	UnsupportedTypePolicy,
];

Deno.test("mod.ts exports exactly the documented runtime surface", () => {
	// Guards against accidental API drift: adding a value export here is a deliberate
	// act that must be reflected in the docs.
	assertEquals(Object.keys(mod).sort(), [
		"DEFAULT_CIRCUIT_COOLDOWN",
		"DEFAULT_CIRCUIT_THRESHOLD",
		"PageFetchError",
		"compose",
		"composeSignal",
		"createCircuitBreaker",
		"createEventsLayer",
		"createFetcher",
		"createRetry",
		"deadlineGuard",
		"defaultIsFailure",
		"defaultIsRetryable",
		"defaultRetryable",
		"httpErrorGuard",
		"parseRetryAfter",
		"resolveDeadline",
		"safeEmit",
		"sleep",
		"timeoutGuard",
	]);
});

Deno.test("adapters.ts exports exactly the documented runtime surface", () => {
	assertEquals(Object.keys(adapters).sort(), [
		"DEFAULT_ACQUIRE_TIMEOUT",
		"DEFAULT_ALLOW_CONTENT_TYPES",
		"DEFAULT_BLOCKED_RESOURCES",
		"DEFAULT_BROWSER_MAX_REDIRECTS",
		"DEFAULT_CAPTURE_LIMIT",
		"DEFAULT_MAX_BYTES",
		"DEFAULT_MAX_DOM_BYTES",
		"DEFAULT_MAX_PAGES_PER_CONTEXT",
		"DEFAULT_MAX_REDIRECTS",
		"DEFAULT_NAVIGATION_TIMEOUT",
		"DEFAULT_NETWORK_IDLE",
		"DEFAULT_POOL_SIZE",
		"DEFAULT_USER_AGENT",
		"DEFAULT_WAIT",
		"applyWait",
		"browserErrorFrom",
		"compileRequestFilter",
		"createBrowserAdapter",
		"createContextPool",
		"createHttpAdapter",
		"decodeText",
		"detectBom",
		"detectExitHookHost",
		"isAllowedContentType",
		"isMetaSniffable",
		"isSupportedEncoding",
		"killProcess",
		"normalizeHeaders",
		"normalizeWait",
		"parseContentType",
		"playwrightDriver",
		"poolShapeFor",
		"puppeteerDriver",
		"readBodyLimited",
		"registerExitHook",
		"sniffCharset",
		"sniffMetaCharset",
	]);
});
